self:
  hosts:
    mgmt:
      ansible_host: localhost

application:
  hosts:
    app1:
      ansible_host: 192.168.63.120

monitoring:
  hosts:
    prometheus:
      ansible_host: 192.168.63.3
  vars:
    git_repo_folder: "/tmp/checkout"
    git_prometheus_config_file: "/home/user/otusobserv/project/configs/prometheus/prometheus.yml"
    prometheus_install_dir: "/opt/prometheus/"

docker:
  hosts:
    docker1:
      ansible_host: 192.168.63.5

all_servers:
  children:
    self:
    application:
    monitoring:
    docker:
