self:
  hosts:
    mgmt:
      ansible_host: localhost

application:
  hosts:
    app1:
      ansible_host: 192.168.63.120

monitoring:
  hosts:
    prometheus:
      ansible_host: 192.168.63.3

docker:
  hosts:
    docker1:
      ansible_host: 192.168.63.5

all_servers:
  children:
    self:
    application:
    monitoring:
    docker:
