- name: playPrometheusSrv
  hosts: prometheus
  tasks:
    - name: Install Git
      become: true
      yum:
        name: git
        state: present

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/neomorphizm34/otusobserv.git'
        dest: "{{ git_repo_folder }}"

    - name: configure prometheus
      become: true
      copy:
        src: "{{ git_prometheus_config_file }}"
        dest: "{{ prometheus_install_dir }}"
        owner: prometheus
        group: prometheus
        mode: 0640
        validate: "{{ prometheus_install_dir }}promtool check config %s"
      notify:
        - reload prometheus