- name: playPrometheusSrv
  hosts: prometheus
  become: true
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present

    - name: configure prometheus
      copy:
        src: "{{ git_prometheus_config_file }}"
        dest: "{{ prometheus_install_dir }}"
        owner: prometheus
        group: prometheus
        mode: 0640
        validate: "{{ prometheus_install_dir }}promtool check config %s"

    - name: restart prometheus
      systemd:
        daemon_reload: true
        name: prometheus
        state: restarted