- name: playPrometheusSrv
  hosts: prometheus
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present
      become: true
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/neomorphizm34/otusobserv.git'
        dest: /tmp/checkout